name: Deploy CA Frontend

on:
  push:
    branches: [ca]

jobs:
  ca-production-deploy:
    if: github.repository == 'CATALOG-Historic-Records/orphaned-wells-ui'
    name: Deploy to Google App Engine
    uses: ./.github/workflows/deploy-dispatch.yml
    with:
      app_yaml: deployment/app-engine/app-ca.yaml
      state: california
      app_environment: ca
    secrets:
      backend_url: ${{ secrets.CA_BACKEND_URL }}
      google_clientid: ${{ secrets.GOOGLE_CLIENTID }}
      gcloud_service_account_json: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_JSON }}
