name: Deploy Osage Frontend

on:
  push:
    branches: [osage]

jobs:
  osage-production-deploy:
    if: github.repository == 'CATALOG-Historic-Records/orphaned-wells-ui'
    name: Deploy to Google App Engine
    uses: ./.github/workflows/deploy-dispatch.yml
    with:
      app_yaml: deployment/app-engine/app-osage.yaml
      collaborator: osage
    secrets:
      backend_url: ${{ secrets.OSAGE_BACKEND_URL }}
      google_clientid: ${{ secrets.GOOGLE_CLIENTID }}
      deployment_service_key_json: ${{ secrets.DEPLOYMENT_SERVICE_KEY_JSON }}
