name: App Tests

on:
  push:

  pull_request:
    branches: [main]

jobs:
  frontend-tests:
    name: Frontend testing
    uses: ./.github/workflows/frontend-tests-dispatch.yml
    with:
      checkout_repository: ${{ github.repository }}
      checkout_ref: ${{ github.sha }}
      app_state: illinois
